[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=61", "setuptools-scm[toml]>=6.2" ]

[project]
name = "cmglaciology"
description = "Colormaps for glaciology"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [
  { name = "Andy Aschwanden", email = "aaschwanden@alaska.edu" },
]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dynamic = [
  "version",
]
dependencies = [
  "matplotlib>=3.6",
  "numpy",
]
optional-dependencies.test = [ "pytest" ]

[tool.setuptools]
packages = [ "cmglaciology" ]
package-data.cmglaciology = [ "cmaps/*.txt", "colormaps.png" ]

[tool.setuptools_scm]

[tool.ruff]
line-length = 120
lint.select = [
  "F", # flakes
  "I", # import sorting
  "U", # upgrade
]

[tool.pyproject-fmt]
column_width = 120
indent = 2
